# Generated by Django 4.0.5 on 2022-06-29 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_event', models.TextField(max_length=150, verbose_name='Titulo')),
                ('event_feature', models.CharField(choices=[('Presencial', 'Presencial'), ('Híbrida', 'Híbrida'), ('Não Presencial', 'Não Presencial')], default='Híbrida', max_length=50)),
                ('date_initial', models.DateField(verbose_name='Data Inicial')),
                ('date_final', models.DateField(verbose_name='Data Final')),
                ('date_to_publication', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Publicação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelaEventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_realizada', models.CharField(choices=[('Apoio Técnico Presencial (ATP)', 'Apoio Técnico Presencial (ATP)'), ('Apoio Técnico Não Presencial (ATNP)', 'Apoio Técnico Não Presencial (ATNP)'), ('Outras Ações', 'Outras Ações')], default='Apoio Técnico Presencial (ATP)', max_length=100)),
                ('tecnico_presencial', models.CharField(choices=[('Encontros de apoio técnico', 'Encontros de apoio técnico'), ('Apoio técnico individualizado no município', 'Apoio técnico individualizado no município'), ('Apoio técnico individualizado na SAAS', 'Apoio técnico individualizado na SAAS'), ('Monitoramento com periodicidade mínima anual', 'Monitoramento com periodicidade mínima anual'), ('Seminários e/ou Oficinas', 'Seminários e/ou Oficinas'), ('Visitas técnicas', 'Visitas técnicas'), ('(Não se aplica)', '(Não se aplica)')], max_length=100)),
                ('tecnico_nao_presencial', models.CharField(choices=[('Centrais de relacionamento', 'Centrais de relacionamento'), ('E-mails, telefonemas e mensagens', 'E-mails, telefonemas e mensagens'), ('Normas, orientações técnicas e materiais informativos', 'Normas, orientações técnicas e materiais informativos'), ('Videoconferências e transmissões ao vivo', 'Videoconferências e transmissões ao vivo'), ('Instrumentos e ferramentas informacionais do SUAS', 'Instrumentos e ferramentas informacionais do SUAS'), ('Sítios eletrônicos e aplicativos', 'Sítios eletrônicos e aplicativos'), ('(Não se Aplica)', '(Não se Aplica)')], max_length=100)),
                ('outras_acoes', models.CharField(choices=[('Apuração de denúncias', 'Apuração de denúncias'), ('Fiscalizações e auditorias', 'Fiscalizações e auditorias'), ('Plano de Providências', 'Plano de Providências'), ('Capacitação', 'Capacitação'), ('Supervisão Técnica', 'Supervisão Técnica'), ('Formação', 'Formação'), ('Manifestação Técnica', 'Manifestação Técnica'), ('Audiência Pública', 'Audiência Pública'), ('(Não se aplica)', '(Não se aplica)'), ('Outros', 'Outros')], max_length=100)),
                ('numbers_employee', models.IntegerField(verbose_name='Numero de Funcionario')),
                ('description_action', models.TextField(max_length=100, verbose_name='Descrição da Ação')),
                ('date_actions', models.DateField(verbose_name='Data')),
                ('date_to_publication', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Publicação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelaAcoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
